name: Building the React App.

on:
    [push]

jobs:
    building-frontend:

        runs-on: ubuntu-latest

        env:
          working-directory: ./frontend

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install npm packages.
              run: npm ci
              working-directory: ${{env.working-directory}}
            - name: Running npm build.
              run: npm run build --if-present
              working-directory: ${{env.working-directory}}
    deploy:
      needs: building-frontend
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.7.8
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP_NAME_STAGING}}
            heroku_email: ${{secrets.USER_EMAIL}}
            usedocker: true
            justlogin: true
        - run: |
             heroku container:login
             git push heroku HEAD:master
